{{/*
Author: Hee Won Lee <knowpd@research.att.com>
Created on: 10/7/2017
*/}}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    version: {{ .Chart.Version }}
    app: ceph
    daemon: mgr
    release: {{ .Release.Name }}
  name: ceph-mgr
spec:
  replicas: {{ .Values.resources.mgr.replicas }}
  template:
    metadata:
      name: ceph-mgr
      labels:
        version: {{ .Chart.Version }}
        app: ceph
        daemon: mgr
        release: {{ .Release.Name }}
    spec:
      serviceAccount: default
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: main
          image: {{ .Values.images.daemon }}
          imagePullPolicy: {{ .Values.image_policy.pull }}
          ports:
            - containerPort: {{ .Values.service.mgr.port }}
          env:
            - name: CEPH_DAEMON
              value: mgr
            - name: MGR_PORT
              value: {{ .Values.service.mgr.port | quote }}
          {{- if .Values.debug_level }}
            - name: DEBUG
              value: {{ .Values.debug_level }}
          {{- end }}
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.resources.mgr.requests.memory | quote }}
              cpu: {{ .Values.resources.mgr.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.mgr.limits.memory | quote }}
              cpu: {{ .Values.resources.mgr.limits.cpu | quote }}
      volumes:
        - name: ceph-conf
          configMap:
            name: ceph-conf
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
